services:

  wordpress:
    image: soulteary/sqlite-wordpress:7.1.0
    # or use: ghcr.io/soulteary/sqlite-wordpress:7.1.0
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
